add features
lgor89/telegram_bot pull request #1
Opened 2017-07-08 20:23 UTC by lgor89

2017-07-08 21:06 UTC, anatoliliotych requested changes

2017-07-08 21:06 UTC, anatoliliotych commented on app/controllers/webhooks_controller.rb
> +	@bot_token = Rails.application.secrets.telegram_token
style guide!

2017-07-08 21:06 UTC, anatoliliotych commented on config/initializers/bot.rb
> +	@url = "https://arcane-savannah-59671.herokuapp.com/"
to constant!

2017-07-11 17:47 UTC, anatoliliotych requested changes

2017-07-11 17:47 UTC, anatoliliotych commented on app/controllers/TEST
> +  1. Move the cursor to this line.
what this file is doing here?

2017-07-11 17:47 UTC, anatoliliotych commented on app/controllers/webhooks_controller.rb
> +    @common_request = "https://api.telegram.org/bot#{@bot_token}/"
move url to constant

2017-07-11 17:47 UTC, anatoliliotych commented on app/controllers/webhooks_controller.rb
> +      uri = URI(@common_request + 'sendMessage' + '?chat_id=' +
please make this more readable

2017-07-11 17:47 UTC, anatoliliotych commented on config/initializers/bot.rb
> +def get_me
check naming for the method

2017-07-15 20:38 UTC, lgor89 commented on app/controllers/TEST
> +  1. Move the cursor to this line.
I don't know. Maybe this is Ruby magic)

2017-07-17 07:05 UTC, anatoliliotych requested changes
This bot with bot gem will take couple lines of code... 
I shouldn't found any gem, wich make updates through webhooks, so wrote myself )

2017-07-17 07:05 UTC, anatoliliotych commented on database.yml
> +./
strange file...

2017-07-17 07:47 UTC, lgor89 commented on database.yml
> +./
where you found it?

2017-07-25 15:19 UTC, anatoliliotych requested changes
Please add readme

2017-07-25 15:19 UTC, anatoliliotych commented on app/controllers/webhooks_controller.rb
> +    if @response.casecmp('start').zero?
not the best way to check if the substring is part of the string

2017-07-25 15:19 UTC, anatoliliotych commented on app/controllers/webhooks_controller.rb
> +      parameters = URI.encode_www_form("chat_id"=>@chat_id.to_s,"text"=>"hello #{@name}")
check style guide

2017-07-25 15:19 UTC, anatoliliotych commented on app/controllers/webhooks_controller.rb
> +      uri = URI(COMMON_REQUEST + 'sendMessage?'+"#{parameters}")
check style guide

2017-07-26 09:23 UTC, closed without merging